---
  database: "~/software/p2p/downpour/playground/data/1/session.db"
  datadir: "~/software/p2p/downpour/playground/data/1/"
  unchokedpeers: 3
  rpcenabled: false
  dhtenabled: false
  # speedlimitdownload: 50
  # speedlimitupload: 50
